<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LocaisImportSeeder extends Seeder
{
    public function run(): void
    {
        // Ensure 'NÃO DEFINIDO' local exists with ID 1
        $localNaoDefinido = \App\Models\Local::find(1);
        if (!$localNaoDefinido) {
            \App\Models\Local::create([
                'id' => 1,
                'nome' => 'NÃO DEFINIDO',
                'regional_id' => 100,
                'cidade' => null,
                'uf' => null,
                'status' => 0,
                'active' => false,
                'db_host' => 'localhost',
                'db_name' => 'sibem_adm_1',
                'db_user' => 'root',
            ]);
        }

        $locais = [
            ['id' => 2, 'nome' => 'ADM - CUBATÃO - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,16432E+13', 'cidade' => 'CUBATÃO', 'uf' => 'SP', 'id_status' => 0, 'id_admrg' => 3],
            ['id' => 3, 'nome' => 'ADM - GUARUJÁ - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,43435E+13', 'cidade' => 'GUARUJÁ', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 3],
            ['id' => 4, 'nome' => 'ADM - SÃO VICENTE - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,16504E+13', 'cidade' => 'SÃO VICENTE', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 3],
            ['id' => 5, 'nome' => 'ADM - SANTOS - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,82517E+13', 'cidade' => 'SANTOS', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 3],
            ['id' => 6, 'nome' => 'ADM - EMBU DAS ARTES - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,6371E+12', 'cidade' => 'EMBU DAS ARTES', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 206],
            ['id' => 7, 'nome' => 'ADM - CAPIVARI - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,69272E+13', 'cidade' => 'CAPIVARI', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 74],
            ['id' => 9, 'nome' => 'ADM - ACRELÂNDIA - AC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,78414E+12', 'cidade' => 'ACRELÂNDIA', 'uf' => 'AC', 'id_status' => 1, 'id_admrg' => 120],
            ['id' => 10, 'nome' => 'ADM - BRASILÉIA - AC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,47071E+13', 'cidade' => 'BRASILÉIA', 'uf' => 'AC', 'id_status' => 1, 'id_admrg' => 120],
            ['id' => 11, 'nome' => 'ADM - CRUZEIRO DO SUL - AC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,44118E+13', 'cidade' => 'CRUZEIRO DO SUL', 'uf' => 'AC', 'id_status' => 1, 'id_admrg' => 120],
            ['id' => 12, 'nome' => 'ADM - PLÁCIDO DE CASTRO - AC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,62072E+12', 'cidade' => 'PLÁCIDO DE CASTRO', 'uf' => 'AC', 'id_status' => 1, 'id_admrg' => 120],
            ['id' => 13, 'nome' => 'ADM - RIO BRANCO - AC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,03285E+12', 'cidade' => 'RIO BRANCO', 'uf' => 'AC', 'id_status' => 1, 'id_admrg' => 120],
            ['id' => 14, 'nome' => 'ADM - SENA MADUREIRA - AC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,38222E+12', 'cidade' => 'SENA MADUREIRA', 'uf' => 'AC', 'id_status' => 1, 'id_admrg' => 120],
            ['id' => 15, 'nome' => 'ADM - XAPURI - AC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,08785E+12', 'cidade' => 'XAPURI', 'uf' => 'AC', 'id_status' => 1, 'id_admrg' => 120],
            ['id' => 16, 'nome' => 'ADM - ARAPIRACA - AL', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,41772E+13', 'cidade' => 'ARAPIRACA', 'uf' => 'AL', 'id_status' => 1, 'id_admrg' => 237],
            ['id' => 17, 'nome' => 'ADM - DELMIRO GOUVEIA - AL', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,80396E+12', 'cidade' => 'DELMIRO GOUVEIA', 'uf' => 'AL', 'id_status' => 1, 'id_admrg' => 237],
            ['id' => 18, 'nome' => 'ADM - MACEIÓ - AL', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,21597E+13', 'cidade' => 'MACEIÓ', 'uf' => 'AL', 'id_status' => 1, 'id_admrg' => 237],
            ['id' => 19, 'nome' => 'ADM - PALMEIRA DOS ÍNDIOS - AL', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,22391E+13', 'cidade' => 'PALMEIRA DOS ÍNDIOS', 'uf' => 'AL', 'id_status' => 1, 'id_admrg' => 237],
            ['id' => 20, 'nome' => 'ADM - APUÍ - AM', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,69351E+12', 'cidade' => 'APUÍ', 'uf' => 'AM', 'id_status' => 1, 'id_admrg' => 156002],
            ['id' => 21, 'nome' => 'ADM - HUMAITÁ - AM', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,3957E+12', 'cidade' => 'HUMAITÁ', 'uf' => 'AM', 'id_status' => 1, 'id_admrg' => 156002],
            ['id' => 22, 'nome' => 'ADM - MANAUS - AM', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,30659E+12', 'cidade' => 'MANAUS', 'uf' => 'AM', 'id_status' => 1, 'id_admrg' => 121],
            ['id' => 23, 'nome' => 'ADM - TEFÉ - AM', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,22181E+12', 'cidade' => 'TEFÉ', 'uf' => 'AM', 'id_status' => 1, 'id_admrg' => 121],
            ['id' => 24, 'nome' => 'ADM - MACAPÁ - AP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,98705E+12', 'cidade' => 'MACAPÁ', 'uf' => 'AP', 'id_status' => 1, 'id_admrg' => 230],
            ['id' => 25, 'nome' => 'ADM - ALAGOINHAS - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32477E+13', 'cidade' => 'ALAGOINHAS', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 122],
            ['id' => 26, 'nome' => 'ADM - APORÁ - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,61321E+13', 'cidade' => 'APORÁ', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 122],
            ['id' => 27, 'nome' => 'ADM - OLINDINA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,33413E+13', 'cidade' => 'OLINDINA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 122],
            ['id' => 28, 'nome' => 'ADM - PAULO AFONSO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,45612E+13', 'cidade' => 'PAULO AFONSO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 125],
            ['id' => 29, 'nome' => 'ADM - BARREIRAS - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,62567E+13', 'cidade' => 'BARREIRAS', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 123],
            ['id' => 30, 'nome' => 'ADM - BOM JESUS DA LAPA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32424E+13', 'cidade' => 'BOM JESUS DA LAPA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 123],
            ['id' => 31, 'nome' => 'ADM - SANTA MARIA DA VITÓRIA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,4364E+13', 'cidade' => 'SANTA MARIA DA VITÓRIA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 123],
            ['id' => 32, 'nome' => 'ADM - CANSANÇÃO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,70914E+12', 'cidade' => 'CANSANÇÃO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 125],
            ['id' => 33, 'nome' => 'ADM - EUCLIDES DA CUNHA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,30816E+13', 'cidade' => 'EUCLIDES DA CUNHA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 125],
            ['id' => 34, 'nome' => 'ADM - ITIÚBA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '9,83217E+11', 'cidade' => 'ITIÚBA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 125],
            ['id' => 35, 'nome' => 'ADM - MONTE SANTO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,14319E+13', 'cidade' => 'MONTE SANTO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 125],
            ['id' => 36, 'nome' => 'ADM - UAUÁ - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,33437E+13', 'cidade' => 'UAUÁ', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 125],
            ['id' => 37, 'nome' => 'ADM - CONCEIÇÃO DO COITÉ - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,2566E+13', 'cidade' => 'CONCEIÇÃO DO COITÉ', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 126],
            ['id' => 38, 'nome' => 'ADM - FEIRA DE SANTANA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,41919E+13', 'cidade' => 'FEIRA DE SANTANA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 126],
            ['id' => 39, 'nome' => 'ADM - IAÇU - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,50234E+12', 'cidade' => 'IAÇU', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 20587],
            ['id' => 40, 'nome' => 'ADM - ITABERABA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,46794E+12', 'cidade' => 'ITABERABA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 20587],
            ['id' => 41, 'nome' => 'ADM - MUTUÍPE - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,47383E+12', 'cidade' => 'MUTUÍPE', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 20587],
            ['id' => 42, 'nome' => 'ADM - SERRINHA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,23431E+13', 'cidade' => 'SERRINHA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 126],
            ['id' => 43, 'nome' => 'ADM - TUCANO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,25248E+13', 'cidade' => 'TUCANO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 126],
            ['id' => 44, 'nome' => 'ADM - VALENTE - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32275E+13', 'cidade' => 'VALENTE', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 126],
            ['id' => 45, 'nome' => 'ADM - ABAÍRA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,4502E+13', 'cidade' => 'ABAÍRA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 127],
            ['id' => 46, 'nome' => 'ADM - BRUMADO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,36719E+13', 'cidade' => 'BRUMADO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 127],
            ['id' => 47, 'nome' => 'ADM - GUANAMBI - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,40972E+13', 'cidade' => 'GUANAMBI', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 127],
            ['id' => 48, 'nome' => 'ADM - PARAMIRIM - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,94373E+13', 'cidade' => 'PARAMIRIM', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 127],
            ['id' => 49, 'nome' => 'ADM - URANDI - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,3177E+13', 'cidade' => 'URANDI', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 127],
            ['id' => 50, 'nome' => 'ADM - ILHÉUS - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,09369E+12', 'cidade' => 'ILHÉUS', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 128],
            ['id' => 51, 'nome' => 'ADM - ITABUNA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,41597E+13', 'cidade' => 'ITABUNA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 128],
            ['id' => 52, 'nome' => 'ADM - ITAPETINGA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,46878E+13', 'cidade' => 'ITAPETINGA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 128],
            ['id' => 53, 'nome' => 'ADM - JEQUIÉ - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,45084E+12', 'cidade' => 'JEQUIÉ', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 131],
            ['id' => 54, 'nome' => 'ADM - MARACÁS - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32314E+13', 'cidade' => 'MARACÁS', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 20587],
            ['id' => 55, 'nome' => 'ADM - BARRA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,84198E+13', 'cidade' => 'BARRA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 124],
            ['id' => 56, 'nome' => 'ADM - JACOBINA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,43013E+13', 'cidade' => 'JACOBINA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 130],
            ['id' => 57, 'nome' => 'ADM - JOÃO DOURADO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,42618E+13', 'cidade' => 'JOÃO DOURADO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 124],
            ['id' => 58, 'nome' => 'ADM - SEABRA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32222E+13', 'cidade' => 'SEABRA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 124],
            ['id' => 59, 'nome' => 'ADM - UTINGA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,82318E+13', 'cidade' => 'UTINGA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 124],
            ['id' => 60, 'nome' => 'ADM - VÁRZEA DA ROÇA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,70233E+12', 'cidade' => 'VÁRZEA DA ROÇA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 130],
            ['id' => 61, 'nome' => 'ADM - CASA NOVA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,3497E+13', 'cidade' => 'CASA NOVA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 129],
            ['id' => 62, 'nome' => 'ADM - CURAÇÁ - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,19977E+12', 'cidade' => 'CURAÇÁ', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 129],
            ['id' => 63, 'nome' => 'ADM - JUAZEIRO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,33492E+13', 'cidade' => 'JUAZEIRO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 129],
            ['id' => 64, 'nome' => 'ADM - REMANSO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,33478E+13', 'cidade' => 'REMANSO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 107703],
            ['id' => 65, 'nome' => 'ADM - CAMAÇARI - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32487E+13', 'cidade' => 'CAMAÇARI', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 132],
            ['id' => 66, 'nome' => 'ADM - CANDEIAS - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,46661E+13', 'cidade' => 'CANDEIAS', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 132],
            ['id' => 68, 'nome' => 'ADM - SANTO ANTÔNIO DE JESUS - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,22425E+13', 'cidade' => 'SANTO ANTÔNIO DE JESUS', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 126],
            ['id' => 69, 'nome' => 'ADM - CAMPO FORMOSO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,7064E+12', 'cidade' => 'CAMPO FORMOSO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 130],
            ['id' => 70, 'nome' => 'ADM - CAPIM GROSSO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,72063E+12', 'cidade' => 'CAPIM GROSSO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 130],
            ['id' => 71, 'nome' => 'ADM - JAGUARARI - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,4576E+13', 'cidade' => 'JAGUARARI', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 130],
            ['id' => 72, 'nome' => 'ADM - SENHOR DO BONFIM - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,31002E+13', 'cidade' => 'SENHOR DO BONFIM', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 130],
            ['id' => 73, 'nome' => 'ADM - EUNÁPOLIS - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,31711E+13', 'cidade' => 'EUNÁPOLIS', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 133],
            ['id' => 74, 'nome' => 'ADM - ITAMARAJU - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,09858E+12', 'cidade' => 'ITAMARAJU', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 133],
            ['id' => 75, 'nome' => 'ADM - ITANHÉM - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32426E+13', 'cidade' => 'ITANHÉM', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 133],
            ['id' => 76, 'nome' => 'ADM - NOVA VIÇOSA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,37851E+12', 'cidade' => 'NOVA VIÇOSA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 133],
            ['id' => 77, 'nome' => 'ADM - PORTO SEGURO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,94829E+13', 'cidade' => 'PORTO SEGURO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 133],
            ['id' => 78, 'nome' => 'ADM - TEIXEIRA DE FREITAS - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,27035E+13', 'cidade' => 'TEIXEIRA DE FREITAS', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 133],
            ['id' => 79, 'nome' => 'ADM - PRADO - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,43825E+13', 'cidade' => 'PRADO', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 133],
            ['id' => 80, 'nome' => 'ADM - UNA - BA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,40960E+13', 'cidade' => 'UNA', 'uf' => 'BA', 'id_status' => 1, 'id_admrg' => 128],
            ['id' => 81, 'nome' => 'ADM - CAUCAIA - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,49168E+12', 'cidade' => 'CAUCAIA', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 82, 'nome' => 'ADM - CRATEÚS - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,92329E+12', 'cidade' => 'CRATEÚS', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 83, 'nome' => 'ADM - FORTALEZA - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,33734E+12', 'cidade' => 'FORTALEZA', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 84, 'nome' => 'ADM - IGUATU - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,3577E+12', 'cidade' => 'IGUATU', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 85, 'nome' => 'ADM - ITAPIPOCA - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,50689E+12', 'cidade' => 'ITAPIPOCA', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 86, 'nome' => 'ADM - JUAZEIRO DO NORTE - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,36021E+12', 'cidade' => 'JUAZEIRO DO NORTE', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 87, 'nome' => 'ADM - LIMOEIRO DO NORTE - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,36026E+12', 'cidade' => 'LIMOEIRO DO NORTE', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 88, 'nome' => 'ADM - MARACANAÚ - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,36024E+12', 'cidade' => 'MARACANAÚ', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 89, 'nome' => 'ADM - QUIXADÁ - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,3644E+12', 'cidade' => 'QUIXADÁ', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 90, 'nome' => 'ADM - SOBRAL - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,3602E+12', 'cidade' => 'SOBRAL', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 91, 'nome' => 'ADM - TIANGUÁ - CE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,36017E+12', 'cidade' => 'TIANGUÁ', 'uf' => 'CE', 'id_status' => 1, 'id_admrg' => 134],
            ['id' => 92, 'nome' => 'ADM - CEILÂNDIA - DF', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,95889E+11', 'cidade' => 'CEILÂNDIA', 'uf' => 'DF', 'id_status' => 1, 'id_admrg' => 135],
            ['id' => 93, 'nome' => 'ADM - GAMA - DF', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '9,0221E+11', 'cidade' => 'GAMA', 'uf' => 'DF', 'id_status' => 1, 'id_admrg' => 135],
            ['id' => 94, 'nome' => 'ADM - PLANALTINA - DF', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,86927E+11', 'cidade' => 'PLANALTINA', 'uf' => 'DF', 'id_status' => 1, 'id_admrg' => 135],
            ['id' => 95, 'nome' => 'ADM - TAGUATINGA - DF', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,95861E+13', 'cidade' => 'TAGUATINGA', 'uf' => 'DF', 'id_status' => 1, 'id_admrg' => 135],
            ['id' => 96, 'nome' => 'ADM - ARACRUZ - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,96735E+13', 'cidade' => 'ARACRUZ', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 141],
            ['id' => 97, 'nome' => 'ADM - BARRA DE SÃO FRANCISCO - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,86105E+13', 'cidade' => 'BARRA DE SÃO FRANCISCO', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 139],
            ['id' => 98, 'nome' => 'ADM - CACHOEIRO DE ITAPEMIRIM - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,86694E+13', 'cidade' => 'CACHOEIRO DE ITAPEMIRIM', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 137],
            ['id' => 99, 'nome' => 'ADM - CARIACICA - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,94073E+13', 'cidade' => 'CARIACICA', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 140],
            ['id' => 100, 'nome' => 'ADM - COLATINA - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,32695E+12', 'cidade' => 'COLATINA', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 139],
            ['id' => 101, 'nome' => 'ADM - LINHARES - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,3274E+12', 'cidade' => 'LINHARES', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 141],
            ['id' => 102, 'nome' => 'ADM - NOVA VENÉCIA - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,32729E+12', 'cidade' => 'NOVA VENÉCIA', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 141],
            ['id' => 103, 'nome' => 'ADM - SÃO MATEUS - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,31945E+12', 'cidade' => 'SÃO MATEUS', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 141],
            ['id' => 104, 'nome' => 'ADM - SÃO ROQUE DO CANAÃ - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,35439E+12', 'cidade' => 'SÃO ROQUE DO CANAÃ', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 139],
            ['id' => 105, 'nome' => 'ADM - SERRA - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,08643E+13', 'cidade' => 'SERRA', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 142],
            ['id' => 106, 'nome' => 'ADM - VENDA NOVA DO IMIGRANTE - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,09349E+13', 'cidade' => 'VENDA NOVA DO IMIGRANTE', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 137],
            ['id' => 107, 'nome' => 'ADM - VIANA - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,09322E+13', 'cidade' => 'VIANA', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 139],
            ['id' => 108, 'nome' => 'ADM - VILA VELHA - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,31936E+12', 'cidade' => 'VILA VELHA', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 138],
            ['id' => 109, 'nome' => 'ADM - VITÓRIA - ES', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,72003E+13', 'cidade' => 'VITÓRIA', 'uf' => 'ES', 'id_status' => 1, 'id_admrg' => 142],
            ['id' => 110, 'nome' => 'ADM - ANÁPOLIS - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,53995E+12', 'cidade' => 'ANÁPOLIS', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 143],
            ['id' => 111, 'nome' => 'ADM - APARECIDA DE GOIÂNIA - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32899E+12', 'cidade' => 'APARECIDA DE GOIÂNIA', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 143],
            ['id' => 112, 'nome' => 'ADM - CALDAS NOVAS - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,50369E+12', 'cidade' => 'CALDAS NOVAS', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 144],
            ['id' => 113, 'nome' => 'ADM - CATALÃO - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,50435E+12', 'cidade' => 'CATALÃO', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 144],
            ['id' => 114, 'nome' => 'ADM - FORMOSA - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,12368E+12', 'cidade' => 'FORMOSA', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 135],
            ['id' => 115, 'nome' => 'ADM - GOIÂNIA - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,53986E+12', 'cidade' => 'GOIÂNIA', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 143],
            ['id' => 116, 'nome' => 'ADM - GOIATUBA - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,50438E+12', 'cidade' => 'GOIATUBA', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 144],
            ['id' => 117, 'nome' => 'ADM - IPORÁ - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,57263E+12', 'cidade' => 'IPORÁ', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 145],
            ['id' => 118, 'nome' => 'ADM - ITUMBIARA - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,50451E+12', 'cidade' => 'ITUMBIARA', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 144],
            ['id' => 119, 'nome' => 'ADM - JATAÍ - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,5726E+12', 'cidade' => 'JATAÍ', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 145],
            ['id' => 120, 'nome' => 'ADM - LUZIÂNIA - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '9,02187E+11', 'cidade' => 'LUZIÂNIA', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 135],
            ['id' => 121, 'nome' => 'ADM - MINEIROS - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,57077E+12', 'cidade' => 'MINEIROS', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 145],
            ['id' => 122, 'nome' => 'ADM - PIRES DO RIO - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,17309E+12', 'cidade' => 'PIRES DO RIO', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 143],
            ['id' => 123, 'nome' => 'ADM - PORANGATU - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,53822E+12', 'cidade' => 'PORANGATU', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 146],
            ['id' => 124, 'nome' => 'ADM - POSSE - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32896E+12', 'cidade' => 'POSSE', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 135],
            ['id' => 125, 'nome' => 'ADM - QUIRINÓPOLIS - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,07416E+12', 'cidade' => 'QUIRINÓPOLIS', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 145],
            ['id' => 126, 'nome' => 'ADM - RIO VERDE - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,57041E+12', 'cidade' => 'RIO VERDE', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 145],
            ['id' => 127, 'nome' => 'ADM - SANTA HELENA DE GOIÁS - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32894E+12', 'cidade' => 'SANTA HELENA DE GOIÁS', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 145],
            ['id' => 128, 'nome' => 'ADM - TRINDADE - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,50367E+12', 'cidade' => 'TRINDADE', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 143],
            ['id' => 129, 'nome' => 'ADM - URUAÇU - GO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,53127E+12', 'cidade' => 'URUAÇU', 'uf' => 'GO', 'id_status' => 1, 'id_admrg' => 146],
            ['id' => 130, 'nome' => 'ADM - AÇAILÂNDIA - MA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,44275E+12', 'cidade' => 'AÇAILÂNDIA', 'uf' => 'MA', 'id_status' => 1, 'id_admrg' => 149],
            ['id' => 131, 'nome' => 'ADM - ALFENAS - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,83313E+13', 'cidade' => 'ALFENAS', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 151],
            ['id' => 132, 'nome' => 'ADM - ALMENARA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,96716E+13', 'cidade' => 'ALMENARA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 165],
            ['id' => 133, 'nome' => 'ADM - ARAÇUAÍ - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,93946E+13', 'cidade' => 'ARAÇUAÍ', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 165],
            ['id' => 134, 'nome' => 'ADM - ARAGUARI - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,69165E+13', 'cidade' => 'ARAGUARI', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 166],
            ['id' => 135, 'nome' => 'ADM - ARAXÁ - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,07718E+13', 'cidade' => 'ARAXÁ', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 166],
            ['id' => 136, 'nome' => 'ADM - BARBACENA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,67503E+13', 'cidade' => 'BARBACENA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 161],
            ['id' => 137, 'nome' => 'ADM - BELO HORIZONTE - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,72729E+13', 'cidade' => 'BELO HORIZONTE', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 147],
            ['id' => 138, 'nome' => 'ADM - BETIM - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,0773E+13', 'cidade' => 'BETIM', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 148],
            ['id' => 139, 'nome' => 'ADM - BOA ESPERANÇA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,71477E+13', 'cidade' => 'BOA ESPERANÇA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 151],
            ['id' => 140, 'nome' => 'ADM - BOM DESPACHO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,72124E+13', 'cidade' => 'BOM DESPACHO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 148],
            ['id' => 141, 'nome' => 'ADM - BRASÍLIA DE MINAS - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,86494E+13', 'cidade' => 'BRASÍLIA DE MINAS', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 150],
            ['id' => 142, 'nome' => 'ADM - CAPELINHA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,66896E+13', 'cidade' => 'CAPELINHA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 165],
            ['id' => 143, 'nome' => 'ADM - CARATINGA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,09633E+13', 'cidade' => 'CARATINGA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 153],
            ['id' => 144, 'nome' => 'ADM - CARMO DO RIO CLARO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,72134E+13', 'cidade' => 'CARMO DO RIO CLARO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 152],
            ['id' => 145, 'nome' => 'ADM - CÁSSIA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,07412E+13', 'cidade' => 'CÁSSIA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 152],
            ['id' => 146, 'nome' => 'ADM - CATAGUASES - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,06013E+13', 'cidade' => 'CATAGUASES', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 160],
            ['id' => 147, 'nome' => 'ADM - CONSELHEIRO LAFAIETE - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,72166E+13', 'cidade' => 'CONSELHEIRO LAFAIETE', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 149],
            ['id' => 148, 'nome' => 'ADM - CONTAGEM - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,07711E+13', 'cidade' => 'CONTAGEM', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 148],
            ['id' => 149, 'nome' => 'ADM - CORINTO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,72159E+13', 'cidade' => 'CORINTO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 150],
            ['id' => 150, 'nome' => 'ADM - CORONEL FABRICIANO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,9939E+13', 'cidade' => 'CORONEL FABRICIANO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 153],
            ['id' => 151, 'nome' => 'ADM - CURVELO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,72153E+13', 'cidade' => 'CURVELO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 150],
            ['id' => 152, 'nome' => 'ADM - DIVINÓPOLIS - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,73299E+13', 'cidade' => 'DIVINÓPOLIS', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 148],
            ['id' => 153, 'nome' => 'ADM - FORMIGA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,73291E+13', 'cidade' => 'FORMIGA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 151],
            ['id' => 154, 'nome' => 'ADM - FRUTAL - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,83679E+13', 'cidade' => 'FRUTAL', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 159],
            ['id' => 155, 'nome' => 'ADM - GOVERNADOR VALADARES - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,66887E+13', 'cidade' => 'GOVERNADOR VALADARES', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 153],
            ['id' => 156, 'nome' => 'ADM - GUAXUPÉ - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,73302E+13', 'cidade' => 'GUAXUPÉ', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 152],
            ['id' => 157, 'nome' => 'ADM - IBIRITÉ - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,07716E+13', 'cidade' => 'IBIRITÉ', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 148],
            ['id' => 158, 'nome' => 'ADM - IPATINGA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,99392E+13', 'cidade' => 'IPATINGA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 153],
            ['id' => 159, 'nome' => 'ADM - ITABIRA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,72175E+13', 'cidade' => 'ITABIRA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 149],
            ['id' => 160, 'nome' => 'ADM - ITAJUBÁ - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,82265E+13', 'cidade' => 'ITAJUBÁ', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 155],
            ['id' => 161, 'nome' => 'ADM - ITUIUTABA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,83674E+13', 'cidade' => 'ITUIUTABA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 166],
            ['id' => 162, 'nome' => 'ADM - JANAÚBA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,86499E+13', 'cidade' => 'JANAÚBA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 150],
            ['id' => 163, 'nome' => 'ADM - JANUÁRIA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,86504E+13', 'cidade' => 'JANUÁRIA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 150],
            ['id' => 164, 'nome' => 'ADM - JOÃO MONLEVADE - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,722E+13', 'cidade' => 'JOÃO MONLEVADE', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 149],
            ['id' => 165, 'nome' => 'ADM - JOÃO PINHEIRO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,51448E+12', 'cidade' => 'JOÃO PINHEIRO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 148],
            ['id' => 166, 'nome' => 'ADM - JUIZ DE FORA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,04403E+13', 'cidade' => 'JUIZ DE FORA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 161],
            ['id' => 167, 'nome' => 'ADM - LAVRAS - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,67531E+13', 'cidade' => 'LAVRAS', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 161],
            ['id' => 168, 'nome' => 'ADM - MANHUAÇU - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,09605E+13', 'cidade' => 'MANHUAÇU', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 153],
            ['id' => 169, 'nome' => 'ADM - MANTENA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,86109E+13', 'cidade' => 'MANTENA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 153],
            ['id' => 170, 'nome' => 'ADM - MONTE CARMELO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,69145E+13', 'cidade' => 'MONTE CARMELO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 166],
            ['id' => 171, 'nome' => 'ADM - MONTES CLAROS - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,86482E+13', 'cidade' => 'MONTES CLAROS', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 150],
            ['id' => 172, 'nome' => 'ADM - MURIAÉ - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,06016E+13', 'cidade' => 'MURIAÉ', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 160],
            ['id' => 173, 'nome' => 'ADM - NANUQUE - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,6689E+13', 'cidade' => 'NANUQUE', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 165],
            ['id' => 174, 'nome' => 'ADM - PARACATU - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,51275E+12', 'cidade' => 'PARACATU', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 148],
            ['id' => 175, 'nome' => 'ADM - PASSOS - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,07414E+13', 'cidade' => 'PASSOS', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 152],
            ['id' => 176, 'nome' => 'ADM - PATOS DE MINAS - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,51444E+12', 'cidade' => 'PATOS DE MINAS', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 148],
            ['id' => 177, 'nome' => 'ADM - PATROCÍNIO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,07727E+13', 'cidade' => 'PATROCÍNIO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 166],
            ['id' => 178, 'nome' => 'ADM - PEDRA AZUL - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,96719E+13', 'cidade' => 'PEDRA AZUL', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 165],
            ['id' => 179, 'nome' => 'ADM - PIRAPORA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,86502E+13', 'cidade' => 'PIRAPORA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 150],
            ['id' => 178, 'nome' => 'ADM - PEDRA AZUL - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,96719E+13', 'cidade' => 'PEDRA AZUL', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 165],
            ['id' => 179, 'nome' => 'ADM - PIRAPORA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,86502E+13', 'cidade' => 'PIRAPORA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 150],
            ['id' => 180, 'nome' => 'ADM - POÇOS DE CALDAS - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,83315E+13', 'cidade' => 'POÇOS DE CALDAS', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 151],
            ['id' => 181, 'nome' => 'ADM - PONTE NOVA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,07718E+13', 'cidade' => 'PONTE NOVA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 149],
            ['id' => 182, 'nome' => 'ADM - POUSO ALEGRE - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,83311E+13', 'cidade' => 'POUSO ALEGRE', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 155],
            ['id' => 183, 'nome' => 'ADM - RIO PARANAÍBA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,0741E+13', 'cidade' => 'RIO PARANAÍBA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 166],
            ['id' => 184, 'nome' => 'ADM - SÃO GOTARDO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,51446E+12', 'cidade' => 'SÃO GOTARDO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 148],
            ['id' => 185, 'nome' => 'ADM - SÃO JOÃO DEL REI - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,67507E+13', 'cidade' => 'SÃO JOÃO DEL REI', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 161],
            ['id' => 186, 'nome' => 'ADM - SÃO LOURENÇO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,83318E+13', 'cidade' => 'SÃO LOURENÇO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 155],
            ['id' => 187, 'nome' => 'ADM - SÃO SEBASTIÃO DO PARAÍSO - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,7147E+13', 'cidade' => 'SÃO SEBASTIÃO DO PARAÍSO', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 152],
            ['id' => 188, 'nome' => 'ADM - SETE LAGOAS - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,72127E+13', 'cidade' => 'SETE LAGOAS', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 150],
            ['id' => 189, 'nome' => 'ADM - TEÓFILO OTONI - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,96738E+13', 'cidade' => 'TEÓFILO OTONI', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 165],
            ['id' => 190, 'nome' => 'ADM - TRÊS CORAÇÕES - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,6916E+13', 'cidade' => 'TRÊS CORAÇÕES', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 155],
            ['id' => 191, 'nome' => 'ADM - TRÊS PONTAS - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,67533E+13', 'cidade' => 'TRÊS PONTAS', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 161],
            ['id' => 192, 'nome' => 'ADM - UBAÍ - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,86506E+13', 'cidade' => 'UBAÍ', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 150],
            ['id' => 193, 'nome' => 'ADM - UBERABA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,83321E+13', 'cidade' => 'UBERABA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 159],
            ['id' => 194, 'nome' => 'ADM - UBERLÂNDIA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,69147E+13', 'cidade' => 'UBERLÂNDIA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 166],
            ['id' => 195, 'nome' => 'ADM - UNAÍ - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '9,02213E+11', 'cidade' => 'UNAÍ', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 135],
            ['id' => 196, 'nome' => 'ADM - VARGINHA - MG', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,69162E+13', 'cidade' => 'VARGINHA', 'uf' => 'MG', 'id_status' => 1, 'id_admrg' => 155],
            ['id' => 197, 'nome' => 'ADM - AQUIDAUANA - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,3112E+12', 'cidade' => 'AQUIDAUANA', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 167],
            ['id' => 198, 'nome' => 'ADM - CAMPO GRANDE - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,30704E+12', 'cidade' => 'CAMPO GRANDE', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 167],
            ['id' => 199, 'nome' => 'ADM - CASSILÂNDIA - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,00569E+13', 'cidade' => 'CASSILÂNDIA', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 168],
            ['id' => 200, 'nome' => 'ADM - CORUMBÁ - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,31122E+12', 'cidade' => 'CORUMBÁ', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 167],
            ['id' => 201, 'nome' => 'ADM - COSTA RICA - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,32694E+12', 'cidade' => 'COSTA RICA', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 167],
            ['id' => 202, 'nome' => 'ADM - COXIM - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,30713E+12', 'cidade' => 'COXIM', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 167],
            ['id' => 203, 'nome' => 'ADM - DOURADOS - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,31126E+12', 'cidade' => 'DOURADOS', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 169],
            ['id' => 204, 'nome' => 'ADM - IVINHEMA - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,32698E+12', 'cidade' => 'IVINHEMA', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 169],
            ['id' => 205, 'nome' => 'ADM - NAVIRAÍ - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,30716E+12', 'cidade' => 'NAVIRAÍ', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 169],
            ['id' => 206, 'nome' => 'ADM - NOVA ANDRADINA - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,32709E+12', 'cidade' => 'NOVA ANDRADINA', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 169],
            ['id' => 207, 'nome' => 'ADM - PARANAÍBA - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,00539E+13', 'cidade' => 'PARANAÍBA', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 168],
            ['id' => 208, 'nome' => 'ADM - PONTA PORÃ - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,34803E+12', 'cidade' => 'PONTA PORÃ', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 169],
            ['id' => 209, 'nome' => 'ADM - TRÊS LAGOAS - MS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,32039E+12', 'cidade' => 'TRÊS LAGOAS', 'uf' => 'MS', 'id_status' => 1, 'id_admrg' => 168],
            ['id' => 210, 'nome' => 'ADM - ALTA FLORESTA - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,49673E+12', 'cidade' => 'ALTA FLORESTA', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 171],
            ['id' => 211, 'nome' => 'ADM - BARRA DO GARÇAS - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,75525E+12', 'cidade' => 'BARRA DO GARÇAS', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 173],
            ['id' => 212, 'nome' => 'ADM - CÁCERES - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,49677E+12', 'cidade' => 'CÁCERES', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 171],
            ['id' => 213, 'nome' => 'ADM - COMODORO - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,16812E+12', 'cidade' => 'COMODORO', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 174],
            ['id' => 214, 'nome' => 'ADM - CUIABÁ - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,74773E+12', 'cidade' => 'CUIABÁ', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 172],
            ['id' => 215, 'nome' => 'ADM - JUÍNA - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,20464E+12', 'cidade' => 'JUÍNA', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 174],
            ['id' => 216, 'nome' => 'ADM - MIRASSOL D\'OESTE - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,4968E+12', 'cidade' => 'MIRASSOL D\'OESTE', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 171],
            ['id' => 217, 'nome' => 'ADM - RONDONÓPOLIS - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,75529E+12', 'cidade' => 'RONDONÓPOLIS', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 173],
            ['id' => 218, 'nome' => 'ADM - SINOP - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,49692E+12', 'cidade' => 'SINOP', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 171],
            ['id' => 219, 'nome' => 'ADM - TANGARÁ DA SERRA - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,49687E+12', 'cidade' => 'TANGARÁ DA SERRA', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 171],
            ['id' => 220, 'nome' => 'ADM - VÁRZEA GRANDE - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,74889E+12', 'cidade' => 'VÁRZEA GRANDE', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 172],
            ['id' => 221, 'nome' => 'ADM - VILA RICA - MT', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,57266E+12', 'cidade' => 'VILA RICA', 'uf' => 'MT', 'id_status' => 1, 'id_admrg' => 173],
            ['id' => 222, 'nome' => 'ADM - BELÉM - PA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,96434E+12', 'cidade' => 'BELÉM', 'uf' => 'PA', 'id_status' => 1, 'id_admrg' => 175],
            ['id' => 223, 'nome' => 'ADM - CASTANHAL - PA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,35649E+12', 'cidade' => 'CASTANHAL', 'uf' => 'PA', 'id_status' => 1, 'id_admrg' => 175],
            ['id' => 224, 'nome' => 'ADM - MARABÁ - PA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,96443E+12', 'cidade' => 'MARABÁ', 'uf' => 'PA', 'id_status' => 1, 'id_admrg' => 176],
            ['id' => 225, 'nome' => 'ADM - REDENÇÃO - PA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,33917E+12', 'cidade' => 'REDENÇÃO', 'uf' => 'PA', 'id_status' => 1, 'id_admrg' => 176],
            ['id' => 226, 'nome' => 'ADM - SANTARÉM - PA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,95748E+12', 'cidade' => 'SANTARÉM', 'uf' => 'PA', 'id_status' => 1, 'id_admrg' => 175],
            ['id' => 227, 'nome' => 'ADM - TUCURUÍ - PA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,96441E+12', 'cidade' => 'TUCURUÍ', 'uf' => 'PA', 'id_status' => 1, 'id_admrg' => 175],
            ['id' => 228, 'nome' => 'ADM - XINGUARA - PA', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,05943E+13', 'cidade' => 'XINGUARA', 'uf' => 'PA', 'id_status' => 1, 'id_admrg' => 176],
            ['id' => 229, 'nome' => 'ADM - CAMPINA GRANDE - PB', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,8813E+12', 'cidade' => 'CAMPINA GRANDE', 'uf' => 'PB', 'id_status' => 1, 'id_admrg' => 177],
            ['id' => 230, 'nome' => 'ADM - GUARABIRA - PB', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,09819E+12', 'cidade' => 'GUARABIRA', 'uf' => 'PB', 'id_status' => 1, 'id_admrg' => 177],
            ['id' => 231, 'nome' => 'ADM - JOÃO PESSOA - PB', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,88195E+12', 'cidade' => 'JOÃO PESSOA', 'uf' => 'PB', 'id_status' => 1, 'id_admrg' => 180],
            ['id' => 232, 'nome' => 'ADM - PATOS - PB', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,88134E+12', 'cidade' => 'PATOS', 'uf' => 'PB', 'id_status' => 1, 'id_admrg' => 178],
            ['id' => 233, 'nome' => 'ADM - POMBAL - PB', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,09817E+12', 'cidade' => 'POMBAL', 'uf' => 'PB', 'id_status' => 1, 'id_admrg' => 178],
            ['id' => 234, 'nome' => 'ADM - SANTA RITA - PB', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,09827E+12', 'cidade' => 'SANTA RITA', 'uf' => 'PB', 'id_status' => 1, 'id_admrg' => 180],
            ['id' => 235, 'nome' => 'ADM - SOUSA - PB', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,09816E+12', 'cidade' => 'SOUSA', 'uf' => 'PB', 'id_status' => 1, 'id_admrg' => 179],
            ['id' => 236, 'nome' => 'ADM - ABREU E LIMA - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,1482E+13', 'cidade' => 'ABREU E LIMA', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 182],
            ['id' => 237, 'nome' => 'ADM - ARARIPINA - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,15297E+13', 'cidade' => 'ARARIPINA', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 181],
            ['id' => 238, 'nome' => 'ADM - CABO DE SANTO AGOSTINHO - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,44038E+13', 'cidade' => 'CABO DE SANTO AGOSTINHO', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 182],
            ['id' => 239, 'nome' => 'ADM - CARUARU - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,04696E+12', 'cidade' => 'CARUARU', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 183],
            ['id' => 240, 'nome' => 'ADM - GARANHUNS - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,12328E+13', 'cidade' => 'GARANHUNS', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 183],
            ['id' => 241, 'nome' => 'ADM - GOIANA - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,14389E+13', 'cidade' => 'GOIANA', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 182],
            ['id' => 242, 'nome' => 'ADM - JABOATÃO DOS GUARARAPES - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,15424E+13', 'cidade' => 'JABOATÃO DOS GUARARAPES', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 182],
            ['id' => 243, 'nome' => 'ADM - OURICURI - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,44037E+13', 'cidade' => 'OURICURI', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 181],
            ['id' => 244, 'nome' => 'ADM - PALMARES - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,148E+13', 'cidade' => 'PALMARES', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 183],
            ['id' => 245, 'nome' => 'ADM - PAULISTA - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,14822E+13', 'cidade' => 'PAULISTA', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 182],
            ['id' => 246, 'nome' => 'ADM - PETROLINA - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,13023E+13', 'cidade' => 'PETROLINA', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 181],
            ['id' => 247, 'nome' => 'ADM - RECIFE - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,44037E+13', 'cidade' => 'RECIFE', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 182],
            ['id' => 248, 'nome' => 'ADM - SALGUEIRO - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,13621E+13', 'cidade' => 'SALGUEIRO', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 181],
            ['id' => 249, 'nome' => 'ADM - SERRA TALHADA - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,13076E+13', 'cidade' => 'SERRA TALHADA', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 181],
            ['id' => 250, 'nome' => 'ADM - VITÓRIA DE SANTO ANTÃO - PE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,14801E+13', 'cidade' => 'VITÓRIA DE SANTO ANTÃO', 'uf' => 'PE', 'id_status' => 1, 'id_admrg' => 183],
            ['id' => 251, 'nome' => 'ADM - CAMPO MAIOR - PI', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,84605E+12', 'cidade' => 'CAMPO MAIOR', 'uf' => 'PI', 'id_status' => 1, 'id_admrg' => 186],
            ['id' => 252, 'nome' => 'ADM - FLORIANO - PI', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,84627E+12', 'cidade' => 'FLORIANO', 'uf' => 'PI', 'id_status' => 1, 'id_admrg' => 186],
            ['id' => 253, 'nome' => 'ADM - PARNAÍBA - PI', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,8461E+12', 'cidade' => 'PARNAÍBA', 'uf' => 'PI', 'id_status' => 1, 'id_admrg' => 186],
            ['id' => 254, 'nome' => 'ADM - PICOS - PI', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,84606E+12', 'cidade' => 'PICOS', 'uf' => 'PI', 'id_status' => 1, 'id_admrg' => 186],
            ['id' => 255, 'nome' => 'ADM - TERESINA - PI', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '6,84591E+12', 'cidade' => 'TERESINA', 'uf' => 'PI', 'id_status' => 1, 'id_admrg' => 186],
            ['id' => 256, 'nome' => 'ADM - APUCARANA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,53825E+13', 'cidade' => 'APUCARANA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 193],
            ['id' => 257, 'nome' => 'ADM - ARAPONGAS - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,53784E+13', 'cidade' => 'ARAPONGAS', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 193],
            ['id' => 258, 'nome' => 'ADM - ASSIS CHATEAUBRIAND - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,77782E+13', 'cidade' => 'ASSIS CHATEAUBRIAND', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 188],
            ['id' => 259, 'nome' => 'ADM - BANDEIRANTES - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,53715E+13', 'cidade' => 'BANDEIRANTES', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 194],
            ['id' => 260, 'nome' => 'ADM - CAMPO MOURÃO - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,5226E+13', 'cidade' => 'CAMPO MOURÃO', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 195],
            ['id' => 261, 'nome' => 'ADM - CASCAVEL - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,62283E+13', 'cidade' => 'CASCAVEL', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 188],
            ['id' => 262, 'nome' => 'ADM - CIANORTE - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,64095E+13', 'cidade' => 'CIANORTE', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 195],
            ['id' => 263, 'nome' => 'ADM - CORNÉLIO PROCÓPIO - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,65415E+13', 'cidade' => 'CORNÉLIO PROCÓPIO', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 194],
            ['id' => 264, 'nome' => 'ADM - CURITIBA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,66107E+13', 'cidade' => 'CURITIBA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 189],
            ['id' => 265, 'nome' => 'ADM - DOIS VIZINHOS - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,65922E+13', 'cidade' => 'DOIS VIZINHOS', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 190],
            ['id' => 266, 'nome' => 'ADM - FOZ DO IGUAÇU - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,70748E+13', 'cidade' => 'FOZ DO IGUAÇU', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 188],
            ['id' => 267, 'nome' => 'ADM - FRANCISCO BELTRÃO - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,6226E+13', 'cidade' => 'FRANCISCO BELTRÃO', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 190],
            ['id' => 268, 'nome' => 'ADM - GOIOERÊ - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,76939E+13', 'cidade' => 'GOIOERÊ', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 195],
            ['id' => 269, 'nome' => 'ADM - GUAÍRA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,6572E+13', 'cidade' => 'GUAÍRA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 197],
            ['id' => 270, 'nome' => 'ADM - GUARAPUAVA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,62262E+13', 'cidade' => 'GUARAPUAVA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 191],
            ['id' => 271, 'nome' => 'ADM - IBAITI - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,66107E+13', 'cidade' => 'IBAITI', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 194],
            ['id' => 272, 'nome' => 'ADM - IRATI - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,59628E+13', 'cidade' => 'IRATI', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 191],
            ['id' => 273, 'nome' => 'ADM - IVAIPORÃ - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,53822E+13', 'cidade' => 'IVAIPORÃ', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 193],
            ['id' => 274, 'nome' => 'ADM - JACAREZINHO - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,53697E+13', 'cidade' => 'JACAREZINHO', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 194],
            ['id' => 275, 'nome' => 'ADM - LONDRINA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,53883E+13', 'cidade' => 'LONDRINA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 192],
            ['id' => 276, 'nome' => 'ADM - MARECHAL CÂNDIDO RONDON - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,64082E+13', 'cidade' => 'MARECHAL CÂNDIDO RONDON', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 197],
            ['id' => 277, 'nome' => 'ADM - MARINGÁ - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,90928E+13', 'cidade' => 'MARINGÁ', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 187],
            ['id' => 278, 'nome' => 'ADM - PARANÁ CIDADE GAÚCHA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,77592E+13', 'cidade' => 'PARANÁ CIDADE GAÚCHA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 195],
            ['id' => 279, 'nome' => 'ADM - PARANAGUÁ - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,65416E+13', 'cidade' => 'PARANAGUÁ', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 189],
            ['id' => 280, 'nome' => 'ADM - PARANAVAÍ - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,89622E+13', 'cidade' => 'PARANAVAÍ', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 187],
            ['id' => 281, 'nome' => 'ADM - PATO BRANCO - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,62287E+13', 'cidade' => 'PATO BRANCO', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 190],
            ['id' => 282, 'nome' => 'ADM - PONTA GROSSA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,59567E+13', 'cidade' => 'PONTA GROSSA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 191],
            ['id' => 283, 'nome' => 'ADM - SANTO ANTÔNIO DA PLATINA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,537E+13', 'cidade' => 'SANTO ANTÔNIO DA PLATINA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 194],
            ['id' => 284, 'nome' => 'ADM - SÃO JOSÉ DOS PINHAIS - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,91799E+13', 'cidade' => 'SÃO JOSÉ DOS PINHAIS', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 189],
            ['id' => 285, 'nome' => 'ADM - TELEMACO BORBA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,59626E+13', 'cidade' => 'TELEMACO BORBA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 191],
            ['id' => 286, 'nome' => 'ADM - TOLEDO - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,6409E+13', 'cidade' => 'TOLEDO', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 197],
            ['id' => 287, 'nome' => 'ADM - UMUARAMA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,70757E+13', 'cidade' => 'UMUARAMA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 195],
            ['id' => 288, 'nome' => 'ADM - UNIÃO DA VITÓRIA - PR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '7,59604E+13', 'cidade' => 'UNIÃO DA VITÓRIA', 'uf' => 'PR', 'id_status' => 1, 'id_admrg' => 191],
            ['id' => 289, 'nome' => 'ADM - BARRA DO PIRAÍ - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,92317E+13', 'cidade' => 'BARRA DO PIRAÍ', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 199],
            ['id' => 290, 'nome' => 'ADM - BOM JESUS DO ITABAPOANA - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,99965E+13', 'cidade' => 'BOM JESUS DO ITABAPOANA', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 200],
            ['id' => 291, 'nome' => 'ADM - CABO FRIO - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,11516E+13', 'cidade' => 'CABO FRIO', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 202],
            ['id' => 292, 'nome' => 'ADM - CAMPOS DOS GOYTACAZES - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,9996E+13', 'cidade' => 'CAMPOS DOS GOYTACAZES', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 200],
            ['id' => 293, 'nome' => 'ADM - DUQUE DE CAXIAS - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,05963E+13', 'cidade' => 'DUQUE DE CAXIAS', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 201],
            ['id' => 294, 'nome' => 'ADM - ITAPERUNA - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,95213E+13', 'cidade' => 'ITAPERUNA', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 200],
            ['id' => 295, 'nome' => 'ADM - MACAÉ - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,99967E+13', 'cidade' => 'MACAÉ', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 202],
            ['id' => 296, 'nome' => 'ADM - NILÓPOLIS - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,06841E+13', 'cidade' => 'NILÓPOLIS', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 198],
            ['id' => 297, 'nome' => 'ADM - NITERÓI - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,11508E+13', 'cidade' => 'NITERÓI', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 202],
            ['id' => 298, 'nome' => 'ADM - NOVA FRIBURGO - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,89679E+13', 'cidade' => 'NOVA FRIBURGO', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 202],
            ['id' => 299, 'nome' => 'ADM - NOVA IGUAÇU - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,06843E+13', 'cidade' => 'NOVA IGUAÇU', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 198],
            ['id' => 300, 'nome' => 'ADM - PETRÓPOLIS - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,24138E+13', 'cidade' => 'PETRÓPOLIS', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 198],
            ['id' => 301, 'nome' => 'ADM - RESENDE - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,9249E+13', 'cidade' => 'RESENDE', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 199],
            ['id' => 302, 'nome' => 'ADM - RIO DE JANEIRO - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,36586E+13', 'cidade' => 'RIO DE JANEIRO', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 201],
            ['id' => 303, 'nome' => 'ADM - TANGUÁ - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,11663E+13', 'cidade' => 'TANGUÁ', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 202],
            ['id' => 304, 'nome' => 'ADM - TERESÓPOLIS - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,89675E+13', 'cidade' => 'TERESÓPOLIS', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 202],
            ['id' => 305, 'nome' => 'ADM - TRÊS RIOS - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,89626E+13', 'cidade' => 'TRÊS RIOS', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 198],
            ['id' => 306, 'nome' => 'ADM - VOLTA REDONDA - RJ', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,92321E+13', 'cidade' => 'VOLTA REDONDA', 'uf' => 'RJ', 'id_status' => 1, 'id_admrg' => 199],
            ['id' => 307, 'nome' => 'ADM - CAICÓ - RN', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,09819E+12', 'cidade' => 'CAICÓ', 'uf' => 'RN', 'id_status' => 1, 'id_admrg' => 205],
            ['id' => 308, 'nome' => 'ADM - MOSSORÓ - RN', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,24571E+12', 'cidade' => 'MOSSORÓ', 'uf' => 'RN', 'id_status' => 1, 'id_admrg' => 203],
            ['id' => 309, 'nome' => 'ADM - NATAL - RN', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,24637E+12', 'cidade' => 'NATAL', 'uf' => 'RN', 'id_status' => 1, 'id_admrg' => 205],
            ['id' => 310, 'nome' => 'ADM - ARIQUEMES - RO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,30635E+13', 'cidade' => 'ARIQUEMES', 'uf' => 'RO', 'id_status' => 1, 'id_admrg' => 206],
            ['id' => 311, 'nome' => 'ADM - CACOAL - RO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,30701E+12', 'cidade' => 'CACOAL', 'uf' => 'RO', 'id_status' => 1, 'id_admrg' => 208],
            ['id' => 312, 'nome' => 'ADM - GUAJARÁ-MIRIM - RO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,30668E+12', 'cidade' => 'GUAJARÁ-MIRIM', 'uf' => 'RO', 'id_status' => 1, 'id_admrg' => 207],
            ['id' => 313, 'nome' => 'ADM - JARU - RO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,30623E+12', 'cidade' => 'JARU', 'uf' => 'RO', 'id_status' => 1, 'id_admrg' => 206],
            ['id' => 314, 'nome' => 'ADM - JI-PARANÁ - RO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,30588E+12', 'cidade' => 'JI-PARANÁ', 'uf' => 'RO', 'id_status' => 1, 'id_admrg' => 208],
            ['id' => 315, 'nome' => 'ADM - OURO PRETO DO OESTE - RO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,30293E+12', 'cidade' => 'OURO PRETO DO OESTE', 'uf' => 'RO', 'id_status' => 1, 'id_admrg' => 208],
            ['id' => 316, 'nome' => 'ADM - PIMENTA BUENO - RO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,30514E+12', 'cidade' => 'PIMENTA BUENO', 'uf' => 'RO', 'id_status' => 1, 'id_admrg' => 209],
            ['id' => 317, 'nome' => 'ADM - PORTO VELHO - RO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,30678E+12', 'cidade' => 'PORTO VELHO', 'uf' => 'RO', 'id_status' => 1, 'id_admrg' => 207],
            ['id' => 318, 'nome' => 'ADM - ROLIM DE MOURA - RO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,2808E+13', 'cidade' => 'ROLIM DE MOURA', 'uf' => 'RO', 'id_status' => 1, 'id_admrg' => 209],
            ['id' => 319, 'nome' => 'ADM - VILHENA - RO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,3052E+12', 'cidade' => 'VILHENA', 'uf' => 'RO', 'id_status' => 1, 'id_admrg' => 209],
            ['id' => 320, 'nome' => 'ADM - BOA VISTA - RR', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,17385E+12', 'cidade' => 'BOA VISTA', 'uf' => 'RR', 'id_status' => 1, 'id_admrg' => 210],
            ['id' => 321, 'nome' => 'ADM - CAÇAPAVA DO SUL - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,86658E+13', 'cidade' => 'CAÇAPAVA DO SUL', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 216],
            ['id' => 322, 'nome' => 'ADM - CAXIAS DO SUL - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,86499E+13', 'cidade' => 'CAXIAS DO SUL', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 211],
            ['id' => 323, 'nome' => 'ADM - ERECHIM - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,7612E+13', 'cidade' => 'ERECHIM', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 212],
            ['id' => 324, 'nome' => 'ADM - IJUÍ - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '9,02102E+13', 'cidade' => 'IJUÍ', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 214],
            ['id' => 325, 'nome' => 'ADM - PASSO FUNDO - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,85117E+13', 'cidade' => 'PASSO FUNDO', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 212],
            ['id' => 326, 'nome' => 'ADM - PELOTAS - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,83796E+13', 'cidade' => 'PELOTAS', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 213],
            ['id' => 327, 'nome' => 'ADM - PORTO ALEGRE - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '9,26668E+13', 'cidade' => 'PORTO ALEGRE', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 211],
            ['id' => 328, 'nome' => 'ADM - RIO GRANDE - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,98115E+13', 'cidade' => 'RIO GRANDE', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 213],
            ['id' => 329, 'nome' => 'ADM - SANTA MARIA - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '9,56059E+13', 'cidade' => 'SANTA MARIA', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 216],
            ['id' => 330, 'nome' => 'ADM - SANTA ROSA - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,99595E+13', 'cidade' => 'SANTA ROSA', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 214],
            ['id' => 331, 'nome' => 'ADM - SANTO ÂNGELO - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,76283E+13', 'cidade' => 'SANTO ÂNGELO', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 214],
            ['id' => 332, 'nome' => 'ADM - SÃO LEOPOLDO - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '9,16523E+13', 'cidade' => 'SÃO LEOPOLDO', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 215],
            ['id' => 333, 'nome' => 'ADM - URUGUAIANA - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,86658E+13', 'cidade' => 'URUGUAIANA', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 216],
            ['id' => 334, 'nome' => 'ADM - VACARIA - RS', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '9,02102E+13', 'cidade' => 'VACARIA', 'uf' => 'RS', 'id_status' => 1, 'id_admrg' => 211],
            ['id' => 335, 'nome' => 'ADM - ARARANGUÁ - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,57771E+13', 'cidade' => 'ARARANGUÁ', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 219],
            ['id' => 336, 'nome' => 'ADM - BALNEÁRIO CAMBORIÚ - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,37324E+13', 'cidade' => 'BALNEÁRIO CAMBORIÚ', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 220],
            ['id' => 337, 'nome' => 'ADM - BLUMENAU - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,2666E+13', 'cidade' => 'BLUMENAU', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 220],
            ['id' => 338, 'nome' => 'ADM - CAÇADOR - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,37326E+13', 'cidade' => 'CAÇADOR', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 221],
            ['id' => 339, 'nome' => 'ADM - CHAPECÓ - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,33373E+13', 'cidade' => 'CHAPECÓ', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 221],
            ['id' => 340, 'nome' => 'ADM - CRICIÚMA - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,37453E+13', 'cidade' => 'CRICIÚMA', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 219],
            ['id' => 341, 'nome' => 'ADM - FLORIANÓPOLIS - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,33367E+13', 'cidade' => 'FLORIANÓPOLIS', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 218],
            ['id' => 342, 'nome' => 'ADM - ITAJAÍ - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,37323E+13', 'cidade' => 'ITAJAÍ', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 220],
            ['id' => 343, 'nome' => 'ADM - JARAGUÁ DO SUL - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,45892E+13', 'cidade' => 'JARAGUÁ DO SUL', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 217],
            ['id' => 344, 'nome' => 'ADM - JOAÇABA - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,45885E+13', 'cidade' => 'JOAÇABA', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 221],
            ['id' => 345, 'nome' => 'ADM - JOINVILLE - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,45894E+13', 'cidade' => 'JOINVILLE', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 217],
            ['id' => 346, 'nome' => 'ADM - LAGES - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,45892E+13', 'cidade' => 'LAGES', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 222],
            ['id' => 347, 'nome' => 'ADM - RIO DO SUL - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,26487E+13', 'cidade' => 'RIO DO SUL', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 220],
            ['id' => 348, 'nome' => 'ADM - SÃO BENTO DO SUL - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,37324E+13', 'cidade' => 'SÃO BENTO DO SUL', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 217],
            ['id' => 349, 'nome' => 'ADM - SÃO MIGUEL DO OESTE - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,33376E+13', 'cidade' => 'SÃO MIGUEL DO OESTE', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 221],
            ['id' => 350, 'nome' => 'ADM - TUBARÃO - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,33388E+13', 'cidade' => 'TUBARÃO', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 219],
            ['id' => 351, 'nome' => 'ADM - ARACAJU - SE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,31046E+13', 'cidade' => 'ARACAJU', 'uf' => 'SE', 'id_status' => 1, 'id_admrg' => 223],
            ['id' => 352, 'nome' => 'ADM - ESTÂNCIA - SE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,31149E+13', 'cidade' => 'ESTÂNCIA', 'uf' => 'SE', 'id_status' => 1, 'id_admrg' => 225],
            ['id' => 353, 'nome' => 'ADM - ITABAIANA - SE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,304E+13', 'cidade' => 'ITABAIANA', 'uf' => 'SE', 'id_status' => 1, 'id_admrg' => 224],
            ['id' => 354, 'nome' => 'ADM - LAGARTO - SE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,3112E+13', 'cidade' => 'LAGARTO', 'uf' => 'SE', 'id_status' => 1, 'id_admrg' => 224],
            ['id' => 355, 'nome' => 'ADM - NOSSA SENHORA DA GLÓRIA - SE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,514E+12', 'cidade' => 'NOSSA SENHORA DA GLÓRIA', 'uf' => 'SE', 'id_status' => 1, 'id_admrg' => 224],
            ['id' => 356, 'nome' => 'ADM - POÇO VERDE - SE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,31047E+13', 'cidade' => 'POÇO VERDE', 'uf' => 'SE', 'id_status' => 1, 'id_admrg' => 224],
            ['id' => 357, 'nome' => 'ADM - PROPRIÁ - SE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,51179E+12', 'cidade' => 'PROPRIÁ', 'uf' => 'SE', 'id_status' => 1, 'id_admrg' => 223],
            ['id' => 358, 'nome' => 'ADM - SIMÃO DIAS - SE', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,31149E+13', 'cidade' => 'SIMÃO DIAS', 'uf' => 'SE', 'id_status' => 1, 'id_admrg' => 224],
            ['id' => 359, 'nome' => 'ADM - ARAGUAÍNA - TO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,61725E+13', 'cidade' => 'ARAGUAÍNA', 'uf' => 'TO', 'id_status' => 1, 'id_admrg' => 226],
            ['id' => 360, 'nome' => 'ADM - AUGUSTINÓPOLIS - TO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,67469E+12', 'cidade' => 'AUGUSTINÓPOLIS', 'uf' => 'TO', 'id_status' => 1, 'id_admrg' => 226],
            ['id' => 361, 'nome' => 'ADM - COLINAS DO TOCANTINS - TO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,63394E+12', 'cidade' => 'COLINAS DO TOCANTINS', 'uf' => 'TO', 'id_status' => 1, 'id_admrg' => 226],
            ['id' => 362, 'nome' => 'ADM - DIANÓPOLIS - TO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '1,32895E+12', 'cidade' => 'DIANÓPOLIS', 'uf' => 'TO', 'id_status' => 1, 'id_admrg' => 227],
            ['id' => 363, 'nome' => 'ADM - GUARAI - TO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,67475E+12', 'cidade' => 'GUARAI', 'uf' => 'TO', 'id_status' => 1, 'id_admrg' => 227],
            ['id' => 364, 'nome' => 'ADM - GURUPI - TO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,63391E+12', 'cidade' => 'GURUPI', 'uf' => 'TO', 'id_status' => 1, 'id_admrg' => 227],
            ['id' => 365, 'nome' => 'ADM - PALMAS - TO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '3,63737E+12', 'cidade' => 'PALMAS', 'uf' => 'TO', 'id_status' => 1, 'id_admrg' => 227],
            ['id' => 366, 'nome' => 'ADM - PARAÍSO DO TOCANTINS - TO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,63333E+12', 'cidade' => 'PARAÍSO DO TOCANTINS', 'uf' => 'TO', 'id_status' => 1, 'id_admrg' => 227],
            ['id' => 367, 'nome' => 'ADM - PORTO NACIONAL - TO', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '2,63331E+12', 'cidade' => 'PORTO NACIONAL', 'uf' => 'TO', 'id_status' => 1, 'id_admrg' => 227],
            ['id' => 368, 'nome' => 'ADM - BAURU - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,46864E+12', 'cidade' => 'BAURU', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 26],
            ['id' => 369, 'nome' => 'ADM - REGISTRO - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,10953E+12', 'cidade' => 'REGISTRO', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 3],
            ['id' => 370, 'nome' => 'ADM - PRAIA GRANDE - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,10959E+12', 'cidade' => 'PRAIA GRANDE', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 3],
            ['id' => 371, 'nome' => 'ADM - MARÍLIA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,7838E+12', 'cidade' => 'MARÍLIA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 61],
            ['id' => 372, 'nome' => 'ADM - ASSIS - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,46853E+12', 'cidade' => 'ASSIS', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 21],
            ['id' => 373, 'nome' => 'ADM - DRACENA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,46856E+12', 'cidade' => 'DRACENA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 34],
            ['id' => 374, 'nome' => 'ADM - ITAPETININGA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,54848E+12', 'cidade' => 'ITAPETININGA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 45],
            ['id' => 375, 'nome' => 'ADM - FARTURA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,69299E+12', 'cidade' => 'FARTURA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 88],
            ['id' => 376, 'nome' => 'ADM - TATUÍ - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,88849E+12', 'cidade' => 'TATUÍ', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 103],
            ['id' => 377, 'nome' => 'ADM - ITAPEVA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,88851E+12', 'cidade' => 'ITAPEVA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 46],
            ['id' => 378, 'nome' => 'ADM - PRESIDENTE PRUDENTE - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,88874E+12', 'cidade' => 'PRESIDENTE PRUDENTE', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 77],
            ['id' => 379, 'nome' => 'ADM - PRESIDENTE EPITÁCIO - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,88877E+12', 'cidade' => 'PRESIDENTE EPITÁCIO', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 76],
            ['id' => 380, 'nome' => 'ADM - PRESIDENTE VENCESLAU - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,88882E+12', 'cidade' => 'PRESIDENTE VENCESLAU', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 100],
            ['id' => 381, 'nome' => 'ADM - TEODORO SAMPAIO - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,8888E+12', 'cidade' => 'TEODORO SAMPAIO', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 76],
            ['id' => 382, 'nome' => 'ADM - ADAMANTINA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,90906E+12', 'cidade' => 'ADAMANTINA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 34],
            ['id' => 383, 'nome' => 'ADM - RANCHARIA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,54859E+12', 'cidade' => 'RANCHARIA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 77],
            ['id' => 384, 'nome' => 'ADM - OSVALDO CRUZ - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,46859E+12', 'cidade' => 'OSVALDO CRUZ', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 34],
            ['id' => 385, 'nome' => 'ADM - IPUÃ - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,56799E+12', 'cidade' => 'IPUÃ', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 39],
            ['id' => 386, 'nome' => 'ADM - SÃO JOAQUIM DA BARRA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,56796E+12', 'cidade' => 'SÃO JOAQUIM DA BARRA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 39],
            ['id' => 387, 'nome' => 'ADM - ITUVERAVA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,56793E+12', 'cidade' => 'ITUVERAVA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 39],
            ['id' => 388, 'nome' => 'ADM - GUAÍRA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,56788E+12', 'cidade' => 'GUAÍRA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 39],
            ['id' => 389, 'nome' => 'ADM - IGARAPAVA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,56791E+12', 'cidade' => 'IGARAPAVA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 39],
            ['id' => 390, 'nome' => 'ADM - PEDREGULHO - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,56804E+12', 'cidade' => 'PEDREGULHO', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 36],
            ['id' => 391, 'nome' => 'ADM - ORLÂNDIA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,56801E+12', 'cidade' => 'ORLÂNDIA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 39],
            ['id' => 392, 'nome' => 'ADM - MIGUELÓPOLIS - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,56798E+12', 'cidade' => 'MIGUELÓPOLIS', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 39],
            ['id' => 393, 'nome' => 'ADM - CANITAR - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,69263E+12', 'cidade' => 'CANITAR', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 88],
            ['id' => 394, 'nome' => 'ADM - CHAVANTES - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,69265E+12', 'cidade' => 'CHAVANTES', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 88],
            ['id' => 395, 'nome' => 'ADM - CERQUEIRA CÉSAR - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,69294E+12', 'cidade' => 'CERQUEIRA CÉSAR', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 20],
            ['id' => 396, 'nome' => 'ADM - MANDURI - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '4,69324E+12', 'cidade' => 'MANDURI', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 20],
            ['id' => 397, 'nome' => 'ADM - IPUMIRIM - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,33385E+13', 'cidade' => 'IPUMIRIM', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 221],
            ['id' => 398, 'nome' => 'ADM - CONCÓRDIA - SC', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '8,33382E+13', 'cidade' => 'CONCÓRDIA', 'uf' => 'SC', 'id_status' => 1, 'id_admrg' => 221],
            ['id' => 399, 'nome' => 'ADM - INDAIATUBA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,02704E+12', 'cidade' => 'INDAIATUBA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 43],
            ['id' => 400, 'nome' => 'ADM - SALTO - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,0271E+12', 'cidade' => 'SALTO', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 43],
            ['id' => 401, 'nome' => 'ADM - ITÚ - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,02693E+12', 'cidade' => 'ITÚ', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 43],
            ['id' => 402, 'nome' => 'ADM - PORTO FELIZ - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,027E+12', 'cidade' => 'PORTO FELIZ', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 103],
            ['id' => 403, 'nome' => 'ADM - CABREÚVA - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,02688E+12', 'cidade' => 'CABREÚVA', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 43],
            ['id' => 404, 'nome' => 'ADM - PERUÍBE - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,10935E+12', 'cidade' => 'PERUÍBE', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 3],
            ['id' => 405, 'nome' => 'ADM - ITANHAÉM - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,1093E+12', 'cidade' => 'ITANHAÉM', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 3],
            ['id' => 406, 'nome' => 'ADM - MONGAGUÁ - SP', 'razao_social' => 'CONGREGAÇÃO CRISTÃ NO BRASIL', 'cnpj' => '5,10941E+12', 'cidade' => 'MONGAGUÁ', 'uf' => 'SP', 'id_status' => 1, 'id_admrg' => 3],
        ];

        // Load remaining locais from parsed file
        if (file_exists(base_path('scripts/locais_part2.php'))) {
            require base_path('scripts/locais_part2.php');
            if (isset($locais_part2) && is_array($locais_part2)) {
                $locais = array_merge($locais, $locais_part2);
            }
        }

        // Preload valid regional IDs
        $validRegionalIds = \App\Models\Regional::pluck('id')->toArray();
        $upsertData = [];

        foreach ($locais as $local) {
            if ($local['id'] == 0)
                continue;
            if ($local['id'] == 1)
                continue;

            $regionalId = $local['id_admrg'];
            if (!in_array($regionalId, $validRegionalIds)) {
                $regionalId = 100;
            }

            $upsertData[] = [
                'id' => $local['id'],
                'nome' => $local['nome'],
                'regional_id' => $regionalId,
                'cidade' => $local['cidade'],
                'uf' => $local['uf'],
                'cnpj' => $local['cnpj'],
                'razao_social' => $local['razao_social'],
                'status' => $local['id_status'],
                'active' => (bool) $local['id_status'],
                'db_host' => 'localhost',
                'db_name' => 'sibem_adm_' . $local['id'],
                'db_user' => 'root',
                'updated_at' => now(),
                'created_at' => now(),
            ];
        }

        foreach (array_chunk($upsertData, 1000) as $chunk) {
            \App\Models\Local::upsert(
                $chunk,
                ['id'],
                ['nome', 'regional_id', 'cidade', 'uf', 'cnpj', 'razao_social', 'status', 'active', 'db_host', 'db_name', 'db_user', 'updated_at']
            );
        }
    }
}
