<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegionaisImportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regionais = [
            ['id' => 100, 'nome' => 'REG - NÃO DEFINIDO', 'uf' => 'ZZ'],
            ['id' => 1, 'nome' => 'REG - SÃO PAULO - SP', 'uf' => 'SP'],
            ['id' => 3, 'nome' => 'REG - SANTOS - SP', 'uf' => 'SP'],
            ['id' => 74, 'nome' => 'REG - PIRACICABA - SP', 'uf' => 'SP'],
            ['id' => 120, 'nome' => 'REG - RIO BRANCO - AC', 'uf' => 'AC'],
            ['id' => 121, 'nome' => 'REG - MANAUS - AM', 'uf' => 'AM'],
            ['id' => 122, 'nome' => 'REG - ALAGOINHAS - BA', 'uf' => 'BA'],
            ['id' => 123, 'nome' => 'REG - BOM JESUS DA LAPA - BA', 'uf' => 'BA'],
            ['id' => 124, 'nome' => 'REG - JOÃO DOURADO - BA', 'uf' => 'BA'],
            ['id' => 125, 'nome' => 'REG - CANSANÇÃO - BA', 'uf' => 'BA'],
            ['id' => 126, 'nome' => 'REG - FEIRA DE SANTANA - BA', 'uf' => 'BA'],
            ['id' => 127, 'nome' => 'REG - GUANAMBI - BA', 'uf' => 'BA'],
            ['id' => 128, 'nome' => 'REG - ITABUNA - BA', 'uf' => 'BA'],
            ['id' => 129, 'nome' => 'REG - JUAZEIRO - BA', 'uf' => 'BA'],
            ['id' => 130, 'nome' => 'REG - SENHOR DO BONFIM - BA', 'uf' => 'BA'],
            ['id' => 131, 'nome' => 'REG - VITÓRIA DA CONQUISTA - BA', 'uf' => 'BA'],
            ['id' => 132, 'nome' => 'REG - SALVADOR - BA', 'uf' => 'BA'],
            ['id' => 133, 'nome' => 'REG - TEIXEIRA DE FREITAS - BA', 'uf' => 'BA'],
            ['id' => 134, 'nome' => 'REG - JUAZEIRO DO NORTE - CE', 'uf' => 'CE'],
            ['id' => 135, 'nome' => 'REG - FORTALEZA - CE', 'uf' => 'CE'],
            ['id' => 136, 'nome' => 'REG - VILA VELHA - ES', 'uf' => 'ES'],
            ['id' => 137, 'nome' => 'REG - BOM JESUS DE GOIÁS - GO', 'uf' => 'GO'],
            ['id' => 138, 'nome' => 'REG - CATALÃO - GO', 'uf' => 'GO'],
            ['id' => 139, 'nome' => 'REG - GOIÂNIA - GO', 'uf' => 'GO'],
            ['id' => 140, 'nome' => 'REG - PIRANHAS - GO', 'uf' => 'GO'],
            ['id' => 141, 'nome' => 'REG - ITUMBIARA - GO', 'uf' => 'GO'],
            ['id' => 142, 'nome' => 'REG - URUAÇU - GO', 'uf' => 'GO'],
            ['id' => 143, 'nome' => 'REG - JATAÍ - GO', 'uf' => 'GO'],
            ['id' => 144, 'nome' => 'REG - INHUMAS - GO', 'uf' => 'GO'],
            ['id' => 145, 'nome' => 'REG - IMPERATRIZ - MA', 'uf' => 'MA'],
            ['id' => 146, 'nome' => 'REG - SÃO LUÍS - MA', 'uf' => 'MA'],
            ['id' => 148, 'nome' => 'REG - CUIABÁ - MT', 'uf' => 'MT'],
            ['id' => 149, 'nome' => 'REG - RONDONÓPOLIS - MT', 'uf' => 'MT'],
            ['id' => 150, 'nome' => 'REG - CANARANA - BA', 'uf' => 'BA'],
            ['id' => 151, 'nome' => 'REG - CAMPO GRANDE - MS', 'uf' => 'MS'],
            ['id' => 152, 'nome' => 'REG - DOURADOS - MS', 'uf' => 'MS'],
            ['id' => 153, 'nome' => 'REG - ARAXÁ - MG', 'uf' => 'MG'],
            ['id' => 155, 'nome' => 'REG - BRASÍLIA DE MINAS - MG', 'uf' => 'MG'],
            ['id' => 156, 'nome' => 'REG - GOVERNADOR VALADARES - MG', 'uf' => 'MG'],
            ['id' => 157, 'nome' => 'REG - GUAXUPÉ - MG', 'uf' => 'MG'],
            ['id' => 159, 'nome' => 'REG - JUIZ DE FORA - MG', 'uf' => 'MG'],
            ['id' => 160, 'nome' => 'REG - MONTE AZUL - MG', 'uf' => 'MG'],
            ['id' => 162, 'nome' => 'REG - MONTES CLAROS - MG', 'uf' => 'MG'],
            ['id' => 163, 'nome' => 'REG - PIRAPORA - MG', 'uf' => 'MG'],
            ['id' => 164, 'nome' => 'REG - POÇOS DE CALDAS - MG', 'uf' => 'MG'],
            ['id' => 166, 'nome' => 'REG - UBERLÂNDIA - MG', 'uf' => 'MG'],
            ['id' => 167, 'nome' => 'REG - VARGINHA - MG', 'uf' => 'MG'],
            ['id' => 168, 'nome' => 'REG - PATOS DE MINAS - MG', 'uf' => 'MG'],
            ['id' => 169, 'nome' => 'REG - BELO HORIZONTE - MG', 'uf' => 'MG'],
            ['id' => 170, 'nome' => 'REG - JANAÚBA - MG', 'uf' => 'MG'],
            ['id' => 171, 'nome' => 'REG - TAIOBEIRAS - MG', 'uf' => 'MG'],
            ['id' => 172, 'nome' => 'REG - ALTAMIRA - PA', 'uf' => 'PA'],
            ['id' => 173, 'nome' => 'REG - BELÉM - PA', 'uf' => 'PA'],
            ['id' => 174, 'nome' => 'REG - REDENÇÃO - PA', 'uf' => 'PA'],
            ['id' => 175, 'nome' => 'REG - SANTARÉM - PA', 'uf' => 'PA'],
            ['id' => 176, 'nome' => 'REG - MARABÁ - PA', 'uf' => 'PA'],
            ['id' => 177, 'nome' => 'REG - CAMPINA GRANDE - PB', 'uf' => 'PB'],
            ['id' => 178, 'nome' => 'REG - APUCARANA - PR', 'uf' => 'PR'],
            ['id' => 179, 'nome' => 'REG - CAMPO MOURÃO - PR', 'uf' => 'PR'],
            ['id' => 180, 'nome' => 'REG - CASCAVEL - PR', 'uf' => 'PR'],
            ['id' => 181, 'nome' => 'REG - CURITIBA - PR', 'uf' => 'PR'],
            ['id' => 182, 'nome' => 'REG - LONDRINA - PR', 'uf' => 'PR'],
            ['id' => 183, 'nome' => 'REG - MARINGÁ - PR', 'uf' => 'PR'],
            ['id' => 184, 'nome' => 'REG - PONTA GROSSA - PR', 'uf' => 'PR'],
            ['id' => 185, 'nome' => 'REG - SANTO ANTÔNIO DA PLATINA - PR', 'uf' => 'PR'],
            ['id' => 186, 'nome' => 'REG - UMUARAMA - PR', 'uf' => 'PR'],
            ['id' => 187, 'nome' => 'REG - GARANHUNS - PE', 'uf' => 'PE'],
            ['id' => 188, 'nome' => 'REG - RECIFE - PE', 'uf' => 'PE'],
            ['id' => 189, 'nome' => 'REG - SERRA TALHADA - PE', 'uf' => 'PE'],
            ['id' => 190, 'nome' => 'REG - PETROLINA - PE', 'uf' => 'PE'],
            ['id' => 191, 'nome' => 'REG - SÃO RAIMUNDO NONATO - PI', 'uf' => 'PI'],
            ['id' => 192, 'nome' => 'REG - TERESINA - PI', 'uf' => 'PI'],
            ['id' => 193, 'nome' => 'REG - NATAL - RN', 'uf' => 'RN'],
            ['id' => 194, 'nome' => 'REG - PORTO ALEGRE - RS', 'uf' => 'RS'],
            ['id' => 195, 'nome' => 'REG - RIO DE JANEIRO - RJ', 'uf' => 'RJ'],
            ['id' => 196, 'nome' => 'REG - RESENDE - RJ', 'uf' => 'RJ'],
            ['id' => 197, 'nome' => 'REG - ITAPERUNA - RJ', 'uf' => 'RJ'],
            ['id' => 198, 'nome' => 'REG - CAÇADOR - SC', 'uf' => 'SC'],
            ['id' => 199, 'nome' => 'REG - ITAJAÍ - SC', 'uf' => 'SC'],
            ['id' => 200, 'nome' => 'REG - JOINVILLE - SC', 'uf' => 'SC'],
            ['id' => 201, 'nome' => 'REG - TUBARÃO - SC', 'uf' => 'SC'],
            ['id' => 203, 'nome' => 'REG - GUARULHOS - SP', 'uf' => 'SP'],
            ['id' => 204, 'nome' => 'REG - OSASCO - SP', 'uf' => 'SP'],
            ['id' => 205, 'nome' => 'REG - SANTO ANDRÉ - SP', 'uf' => 'SP'],
            ['id' => 206, 'nome' => 'REG - EMBU DAS ARTES - SP', 'uf' => 'SP'],
            ['id' => 207, 'nome' => 'REG - AMPARO - SP', 'uf' => 'SP'],
            ['id' => 208, 'nome' => 'REG - ARAÇATUBA - SP', 'uf' => 'SP'],
            ['id' => 209, 'nome' => 'REG - ARARAQUARA - SP', 'uf' => 'SP'],
            ['id' => 210, 'nome' => 'REG - ATIBAIA - SP', 'uf' => 'SP'],
            ['id' => 211, 'nome' => 'REG - BAURU - SP', 'uf' => 'SP'],
            ['id' => 212, 'nome' => 'REG - CAMPINAS - SP', 'uf' => 'SP'],
            ['id' => 213, 'nome' => 'REG - CATANDUVA - SP', 'uf' => 'SP'],
            ['id' => 214, 'nome' => 'REG - FERNANDÓPOLIS - SP', 'uf' => 'SP'],
            ['id' => 215, 'nome' => 'REG - ITAÍ - SP', 'uf' => 'SP'],
            ['id' => 216, 'nome' => 'REG - ITAPEVA - SP', 'uf' => 'SP'],
            ['id' => 217, 'nome' => 'REG - JUNDIAÍ - SP', 'uf' => 'SP'],
            ['id' => 218, 'nome' => 'REG - OSVALDO CRUZ - SP', 'uf' => 'SP'],
            ['id' => 219, 'nome' => 'REG - PINDAMONHANGABA - SP', 'uf' => 'SP'],
            ['id' => 221, 'nome' => 'REG - PORTO FERREIRA - SP', 'uf' => 'SP'],
            ['id' => 222, 'nome' => 'REG - PRESIDENTE PRUDENTE - SP', 'uf' => 'SP'],
            ['id' => 223, 'nome' => 'REG - REGISTRO - SP', 'uf' => 'SP'],
            ['id' => 224, 'nome' => 'REG - RIBEIRÃO PRETO - SP', 'uf' => 'SP'],
            ['id' => 226, 'nome' => 'REG - SÃO JOÃO DA BOA VISTA - SP', 'uf' => 'SP'],
            ['id' => 227, 'nome' => 'REG - SOROCABA - SP', 'uf' => 'SP'],
            ['id' => 228, 'nome' => 'REG - ARACAJU - SE', 'uf' => 'SE'],
            ['id' => 229, 'nome' => 'REG - BRASÍLIA - DF', 'uf' => 'DF'],
            ['id' => 230, 'nome' => 'REG - MACAPÁ - AP', 'uf' => 'AP'],
            ['id' => 231, 'nome' => 'REG - JI-PARANÁ - RO', 'uf' => 'RO'],
            ['id' => 232, 'nome' => 'REG - ARIQUEMES - RO', 'uf' => 'RO'],
            ['id' => 233, 'nome' => 'REG - PORTO VELHO - RO', 'uf' => 'RO'],
            ['id' => 234, 'nome' => 'REG - PIMENTA BUENO - RO', 'uf' => 'RO'],
            ['id' => 235, 'nome' => 'REG - BOA VISTA - RR', 'uf' => 'RR'],
            ['id' => 236, 'nome' => 'REG - PALMAS - TO', 'uf' => 'TO'],
            ['id' => 237, 'nome' => 'REG - MACEIÓ - AL', 'uf' => 'AL'],
            ['id' => 20587, 'nome' => 'REG - MARACÁS - BA', 'uf' => 'BA'],
            ['id' => 20588, 'nome' => 'REG - SINOP - MT', 'uf' => 'MT'],
            ['id' => 20589, 'nome' => 'REG - JANUÁRIA - MG', 'uf' => 'MG'],
            ['id' => 20590, 'nome' => 'REG - SALINAS - MG', 'uf' => 'MG'],
            ['id' => 20591, 'nome' => 'REG - LAVRAS - MG', 'uf' => 'MG'],
            ['id' => 20592, 'nome' => 'REG - PARANAVAÍ - PR', 'uf' => 'PR'],
            ['id' => 22494, 'nome' => 'REG - CARUARU - PE', 'uf' => 'PE'],
            ['id' => 23846, 'nome' => 'REG - BARRA DO GARÇAS - MT', 'uf' => 'MT'],
            ['id' => 24378, 'nome' => 'REG - PICOS - PI', 'uf' => 'PI'],
            ['id' => 24791, 'nome' => 'REG - CÁCERES - MT', 'uf' => 'MT'],
            ['id' => 26976, 'nome' => 'REG - SANTA LUZIA - MG', 'uf' => 'MG'],
            ['id' => 26977, 'nome' => 'REG - DIAMANTINA - MG', 'uf' => 'MG'],
            ['id' => 26978, 'nome' => 'REG - OURO PRETO - MG', 'uf' => 'MG'],
            ['id' => 26979, 'nome' => 'REG - FORMIGA - MG', 'uf' => 'MG'],
            ['id' => 26980, 'nome' => 'REG - PONTE NOVA - MG', 'uf' => 'MG'],
            ['id' => 26981, 'nome' => 'REG - POUSO ALEGRE - MG', 'uf' => 'MG'],
            ['id' => 26982, 'nome' => 'REG - SANTA MARIA - RS', 'uf' => 'RS'],
            ['id' => 28249, 'nome' => 'REG - DUQUE DE CAXIAS - RJ', 'uf' => 'RJ'],
            ['id' => 28250, 'nome' => 'REG - MACAÉ - RJ', 'uf' => 'RJ'],
            ['id' => 28533, 'nome' => 'REG - ITAITUBA - PA', 'uf' => 'PA'],
            ['id' => 28795, 'nome' => 'REG - TATUÍ - SP', 'uf' => 'SP'],
            ['id' => 29184, 'nome' => 'REG - ALTA FLORESTA - MT', 'uf' => 'MT'],
            ['id' => 29185, 'nome' => 'REG - MOSSORÓ - RN', 'uf' => 'RN'],
            ['id' => 31542, 'nome' => 'REG - FAINA - GO', 'uf' => 'GO'],
            ['id' => 31598, 'nome' => 'REG - JUÍNA - MT', 'uf' => 'MT'],
            ['id' => 32111, 'nome' => 'REG - NOVA FRIBURGO - RJ', 'uf' => 'RJ'],
            ['id' => 32112, 'nome' => 'REG - OURICURI - PE', 'uf' => 'PE'],
            ['id' => 32113, 'nome' => 'REG - IPATINGA - MG', 'uf' => 'MG'],
            ['id' => 33077, 'nome' => 'REG - TAUÁ - CE', 'uf' => 'CE'],
            ['id' => 33261, 'nome' => 'REG - PASSO FUNDO - RS', 'uf' => 'RS'],
            ['id' => 35828, 'nome' => 'REG - ANGRA DOS REIS - RJ', 'uf' => 'RJ'],
            ['id' => 35976, 'nome' => 'REG - TANGARÁ DA SERRA - MT', 'uf' => 'MT'],
            ['id' => 36454, 'nome' => 'REG - COROATÁ - MA', 'uf' => 'MA'],
            ['id' => 36455, 'nome' => 'REG - NOVA IGUAÇÚ - RJ', 'uf' => 'RJ'],
            ['id' => 36517, 'nome' => 'REG - NOVO HAMBURGO - RS', 'uf' => 'RS'],
            ['id' => 36911, 'nome' => 'REG - MANGA - MG', 'uf' => 'MG'],
            ['id' => 39248, 'nome' => 'REG - SÃO MATEUS - ES', 'uf' => 'ES'],
            ['id' => 39383, 'nome' => 'REG - MAURITI - CE', 'uf' => 'CE'],
            ['id' => 39384, 'nome' => 'REG - RUSSAS - CE', 'uf' => 'CE'],
            ['id' => 39385, 'nome' => 'REG - CAXAMBU - MG', 'uf' => 'MG'],
            ['id' => 72380, 'nome' => 'REG - CACHOEIRO DE ITAPEMIRIM - ES', 'uf' => 'ES'],
            ['id' => 73380, 'nome' => 'REG - FLORIANÓPOLIS - SC', 'uf' => 'SC'],
            ['id' => 73381, 'nome' => 'REG - CHAPECÓ - SC', 'uf' => 'SC'],
            ['id' => 104564, 'nome' => 'REG - SÃO GONÇALO - RJ', 'uf' => 'RJ'],
            ['id' => 104565, 'nome' => 'REG - SOBRAL - CE', 'uf' => 'CE'],
            ['id' => 107703, 'nome' => 'REG - REMANSO - BA', 'uf' => 'BA'],
            ['id' => 107704, 'nome' => 'REG - MOGI DAS CRUZES - SP', 'uf' => 'SP'],
            ['id' => 156002, 'nome' => 'REG - HUMAITÁ - AM', 'uf' => 'AM'],
        ];

        foreach ($regionais as $regional) {
            if ($regional['id'] == 0)
                continue; // Skip ID 0 if database doesn't allow it or handle separately

            \App\Models\Regional::updateOrCreate(
                ['id' => $regional['id']],
                [
                    'nome' => $regional['nome'],
                    'uf' => $regional['uf'],
                    'active' => true
                ]
            );
        }
    }
}
